### ISSUE TITLE
Add support for WowUp

### ISSUE THREAD

**Issue by jimsimon** [DeadlyBossMods/DBM-Unified#116]
CurseForge/Overwolf has blocked WowUp from accessing files hosted on its server. Please consider also publishing to WoWInterface or WowUpHub: https://wowup.io/guide/wowup/hub

**Comment by MysticalOS** [comment]
DBM is on wow interface, and wago. enable wago in wowup is best way to ensure you get it through wowup.

**Comment by jimsimon** [comment]
Awesome, thank you for the quick response!
