### ISSUE TITLE
/dbm hud arrow not working (arithmetic on nil)

### ISSUE THREAD

**Issue by Anonomit** [DeadlyBossMods/DBM-Unified#133]
**Describe the bug**

The hud arrow does not work, and gives a lua error.

**Do you have an error log of what happened?**

1x DBM-Core\DBM-HudMap.lua:420: attempt to perform arithmetic on local 'w' (a nil value)
[string "@DBM-Core\DBM-HudMap.lua"]:420: in function <DBM-Core\DBM-HudMap.lua:393>
[string "@DBM-Core\DBM-HudMap.lua"]:670: in function 'Update'
[string "@DBM-Core\DBM-HudMap.lua"]:618: in function 'UpdateAll'
[string "@DBM-Core\DBM-HudMap.lua"]:1334: in function 'Update'
[string "@DBM-Core\DBM-HudMap.lua"]:285: in function <DBM-Core\DBM-HudMap.lua:254>
[string "@DBM-Core\DBM-HudMap.lua"]:308: in function <DBM-Core\DBM-HudMap.lua:307>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14

**To Reproduce**
1. Target a player in your party/raid
2. Enter `/dbm hud arrow target`
3. See error

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but I can fix the problem with minor adjustments in DBM-HudMap.lua.

**Which version of DeadlyBossMods are you using?**
DBM 2.5.37 (2022/06/07 18:45:26) / VPVEM: v12
TBC PTR client

**Was it working in a previous version? If yes, which was the last good one?**
Without downdating to test, it appears to have been broken in 6ad6b54fcfc1e634d42a36e6167beaa366bbdcd5 with the following changes:
https://github.com/DeadlyBossMods/DBM-Unified/commit/6ad6b54fcfc1e634d42a36e6167beaa366bbdcd5#diff-d86b1e33ce8a094fea9fb79124662f9e14ab4ccdf30fba070afba5a7985b0d9bL415
https://github.com/DeadlyBossMods/DBM-Unified/commit/6ad6b54fcfc1e634d42a36e6167beaa366bbdcd5#diff-d86b1e33ce8a094fea9fb79124662f9e14ab4ccdf30fba070afba5a7985b0d9bL675
https://github.com/DeadlyBossMods/DBM-Unified/commit/6ad6b54fcfc1e634d42a36e6167beaa366bbdcd5#diff-d86b1e33ce8a094fea9fb79124662f9e14ab4ccdf30fba070afba5a7985b0d9bL695

**Additional context**
Reverting the above 3 lines appears to fix the issue. The hud arrow is functional and does not give an error. I don't know which parameters are actually intended to be taken by DrawRouteLineCustom, but I see no issues with the hud after applying the changes.

As an aside, the name matching doesn't appear to work either. The help text indicates that I should be able to do `/dbm hud arrow Playername` and it will draw an arrow to Playername in my party/raid. I haven't been able to get this to work. I am aware that it's case sensitive.

**Comment by MysticalOS** [comment]
I'll let @QartemisT fix this as it was she who broke it
