### ISSUE TITLE
GUI: lua error with https://github.com/DeadlyBossMods/DBM-Unified/commit/62e6f0b06645cb925e2d8bbdbeabaeb041372f74

### ISSUE THREAD

**Issue by Zidras** [DeadlyBossMods/DBM-Unified#140]
**Describe the bug**

https://github.com/DeadlyBossMods/DBM-Unified/commit/62e6f0b06645cb925e2d8bbdbeabaeb041372f74 introduced lua error if ability button is clicked.

**Do you have an error log of what happened?**
```
Message: bad argument #1 to '?' (table expected, got nil)
Time: Sat Jul 30 00:45:29 2022
Count: 1
Stack: bad argument #1 to '?' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\SharedXML\OptionsFrameTemplates.lua"]:6: in function `(for generator)'
[string "@Interface\SharedXML\OptionsFrameTemplates.lua"]:107: in function `OptionsList_ClearSelection'
[string "@Interface\SharedXML\OptionsFrameTemplates.lua"]:147: in function `OptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: 
```

```
Message: Interface\SharedXML\OptionsFrameTemplates.lua:94: attempt to index local 'panel' (a nil value)
Time: Sat Jul 30 00:45:29 2022
Count: 1
Stack: Interface\SharedXML\OptionsFrameTemplates.lua:94: attempt to index local 'panel' (a nil value)
[string "=[C]"]: ?
[string "@Interface\SharedXML\OptionsFrameTemplates.lua"]:94: in function `OptionsList_DisplayPanel'
[string "@Interface\SharedXML\OptionsFrameTemplates.lua"]:150: in function `OptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: 
```

**To Reproduce**

1. Click the outside of the button, as shown in the video.

https://user-images.githubusercontent.com/10605951/181861281-719b4681-9f7e-41c9-917a-1d3a1b69452f.mp4

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but is reproducible and revertible with abovementioned commit.

**Which version of DeadlyBossMods are you using?**
<img width="215" alt="image" src="https://user-images.githubusercontent.com/10605951/181861445-d2256f4f-b10f-4bf9-8cd5-a62d1800058d.png">

**Was it working in a previous version? If yes, which was the last good one?**
Yes.

**Additional context**

**Comment by QartemisT** [comment]
Might have to find a "cleaner hack" sooner or later, as it was removed as apparently (according to dragonflight), false / nil is NEVER a valid type. I guess the fact that retail accepts it just shows how bad the API is :P
