### ISSUE TITLE
Potential problem in the code

### ISSUE THREAD

**Issue by lordtgm** [DeadlyBossMods/DBM-Unified#199]
[in this line](https://github.com/DeadlyBossMods/DBM-Unified/blob/master/DBM-Core/DBM-Core.lua#L1140), select is used which returns all of the items after the index, not the item at the index itself. as I see, the function isnt called with more than 1 argument so its fine. but if you use multiple arguments it can lead to bugs. to solve, just surrond the select function with ().

**Comment by MysticalOS** [comment]
I can see that yeah. I guess with line above it, it wouldn't matter much since it's already iterating over each arg one at a time anyways. I'd imagine for that reason tandanu saw no reason to scope it to first arg only. I'll leave it to @QartemisT though :)

**Comment by Mitalie** [comment]
If there are more values on the right hand side of an assignment than variables on the left hand side, the extra values are ignored and `event` gets set to first return value of `select` no matter how many there are. Wrapping in `( )` to prevent unexpected multiple values is only useful as the last argument of function call `g(1, 2, f())`, last argument of return statement `return 1, 2, f()`, and last argument of array-style table constructor `{1, 2, f()}`.

You could do `a, b = (f())` to ensure b is set to nil, but I'd argue that's bad and potentially confusing code style regardless of wrapping in parentheses or not, and is better written as separate assignments or as `a, b = f(), nil`.

**Comment by QartemisT** [comment]
Cleaner solution is likely to just wrap utilise ipairs instead anyway, than this nasty select mess. (yes, it's fractionally slower, but the frequency that the function is called)
