### ISSUE TITLE
Duplicated fonts in dropdown - conflict with LibSharedMedia

### ISSUE THREAD

**Issue by Zidras** [DeadlyBossMods/DBM-Unified#207]
**Describe the bug**

Some blizzard fonts are duplicated since they are being added twice with different paths (case-sensitive).

**Do you have an error log of what happened?**

N.A.

**To Reproduce**
1. Open font dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/10605951/231592850-46cd1dcb-b1da-487b-b23b-a8ff3d3f3140.png)
![image](https://user-images.githubusercontent.com/10605951/231592864-4c44815c-f447-41bd-91b9-ff20a738babe.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes 

**Which version of DeadlyBossMods are you using?**
<img width="273" alt="image" src="https://user-images.githubusercontent.com/10605951/231593149-e468e1c2-beae-4805-8fec-4775df0e1533.png">

**Was it working in a previous version? If yes, which was the last good one?**
No

**Additional context**
https://github.com/DeadlyBossMods/DBM-Unified/blob/a805496b1b1af3fc5c76f2db4d8be1c4d27d9cb2/DBM-GUI/modules/options/alerts/Announcements.lua#L17-L35
**vs**

LibSharedMedia:
![image](https://user-images.githubusercontent.com/10605951/231593496-a6859092-9261-4673-a7ff-d6531e8b80c4.png)

@QartemisT , this seems your AoE. I'd suggest either delete the duplicate font registration in each module or align fontpath, like so:
```lua
	{
		text	= "Skurri",
		value	= "Fonts\\SKURRI_CYR.TTF"
	},
	{
		text	= "Morpheus",
		value	= "Fonts\\MORPHEUS_CYR.TTF"
	}
```

Also, during the investigation, I found that Friz Quadrata TT does not save as such, and always defaults to Default font (on EN language, at least). Is this a bug or intended?
Feel free to comment on any topic and I'll revert as soon as I can.

**Comment by QartemisT** [comment]
Located both bugs (friz quadrata not keeping variable, and duplicate items). Will be pushing fix shortly :)
