### ISSUE TITLE
DBT: add visual element to represent timer variance window

### ISSUE THREAD

**Issue by Zidras** [DeadlyBossMods/DBM-Unified#265]
**Is your feature request related to a problem? Please describe.**
Currently, when there is a time/cooldown window, DBM strives to code the lowest timer possible, and only rely on the cd object and tilde `~` to identify that the timer is not set in stone and will not be accurate 100% of the time.
Today, https://github.com/DeadlyBossMods/DBM-Unified/commit/95549fffac5e4f1376aac898fe39ac437853fdad was pushed that moves the `~` next to the timer text (most welcome change!), but many users without this math knowledge would still not know how to interpret this information (personal opinion), and would not know when a certain mechanic could be expected (1 second variance? 3 seconds ? 10 seconds?...), especially since timers without explicit `keep` boolean would simply disappear, thus leaving the user guessing whether or not the ability is yet to happen, and when could it happen.

**Describe the solution you'd like**
I have seen in Discord this idea thrown around a couple of times, but never elaborated on nor registered in the tracker.
This is a very gross visualization to showcase the idea:
![image](https://github.com/DeadlyBossMods/DBM-Unified/assets/10605951/2a6f6239-90a8-4419-b251-e1f843cafecf)

https://github.com/DeadlyBossMods/DBM-Unified/assets/10605951/469a6a99-fdfe-4b53-8d8b-29e6e2357a6f

In writing, it could behave as such:

- minimum timer in the variance window = `timer` argument (current DBM behaviour, so no change here is expected* **OR** rework to something like string parsing "[28-32]")
- maximum timer in the variance window = new/reworked argument (e.g.: `timerMax`* **OR** see above 2nd way)
- variance window be embedded in the timer statusbar (e.g.: sectioned, or diferent color/pattern, or text)
- Timer bar only stops when it reaches the maximum hardcoded timer (`timerMax or timer`), or if a :Start is fired again to overwrite it (an overwrite during this coded variance window would not trigger early refresh debug)

(*) food for thought here: this would be fixed on mod load, meaning that it would apply everytime the timer is Started (`timerABC:Start()` would always apply the same metadata that was set on creation, whenever it was used).
If the dev would need to code a specific timer Start on a specific point in the fight (say, 2nd cast on 2nd phase...) with a different window, it would not be possible unless the :Start method had been reworked. For example, `timerABC:Start("[28-32]")` 

**Describe alternatives you've considered**
`keep` argument exists in Core but is seldomly used, but having negative timers would also not be logical for the user, hence my request to further improve on the implementation.
@QartemisT , DBT is your area, so pinging in advance, thank you.

**Comment by MysticalOS** [comment]
I requested this ages ago, artemis just has no time
