### ISSUE TITLE
AddMsg global leaking

### ISSUE THREAD

**Issue by Zidras** [DeadlyBossMods/DBM-Unified#266]
https://github.com/DeadlyBossMods/DBM-Unified/blob/cf52fd3c8ad0616c2e8e10b76a979868b342b1e0/DBM-Core/DBM-Core.lua#L6707

Is there a reason this is a global?

**Comment by MysticalOS** [comment]
it's not global, see line 435
`local currentSpecID, currentSpecName, currentSpecGroup, pformat, loadOptions, checkWipe, checkBossHealth, checkCustomBossHealth, fireEvent, LastInstanceType, breakTimerStart, AddMsg, delayedFunction, handleSync, savedDifficulty, difficultyText, difficultyIndex, lastGroupLeader`

**Comment by Zidras** [comment]
Ah apologies for my blindness
