### ISSUE TITLE
[Bug] Panels fail to load if two or more panels have exact same boss name

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DBM-Unified#291]
**Describe the bug**
It doesn't show a option panel and trash mob category is gone now

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Moved to core since bug is in core
