### ISSUE TITLE
Range check fails in WotLK Classic Saurfang Encounter

### ISSUE THREAD

**Issue by opatut** [DeadlyBossMods/DBM-Unified#302]
While the previous issue with the range finder in the blood prince council encounter seems to resolved by my fix (https://github.com/DeadlyBossMods/DBM-Unified/pull/293), there is still an issue with the range finder in the [Deathbringer Saurfang](https://github.com/DeadlyBossMods/DBM-WotLK/blob/ffa9f233e3f0cf735aed06a79a9ecd88542e142e/DBM-Raids-WoTLK/Icecrown/TheLowerSpire/Deathbringer.lua) encounter. This seems not to be related to the GUI opening incorrectly, as neither the fix nor manually setting the range helps.

**Describe the bug**

The range finder _sometimes_ shows no other players, regardless of distance. If you move out of the zone and port back in (either via the teleporters in ICC or probably also via warlock port or logout/login) the finder starts working again. It breaks again when you move to the gunship that is parked next to the balcony and back onto the balcony. It might thus be related to vehicle physics.

**Do you have an error log of what happened?**

I checked, there was no error logs in Bugsack.

However, I did some experiments and it seems that the check of `IsItemInRange` is not providing accurate results in this position. This might be a WoW bug and not a plugin bug, but maybe you can find a workaround? I tested this by writing into the chat frame:

```
/script print(IsItemInRange(32321, "raid10"))
```

(raid10 was my experimentation buddy in the raid)

**To Reproduce**

1. Go to ICC (10 non-heroic, or probably other modes too)
2. Defeat first three bosses
3. Stand on the balcony where the fight with Saurfang takes place
4. Type `/range 13`
5. Range check window appears, but is always empty. This remains the case for the whole fight.

**Which version of DeadlyBossMods are you using?**

* DBM 3.4.54 alpha (2023/10/30 23:29:59)
* DBM 3.4.53 (2023/10/14 08:17:59)

**Comment by MysticalOS** [comment]
Does that item range work in other places? it may be that the platform/area itself breaks it somehow and not the specific range/item. if so there is NOTHING that can be done. if it's simply that 32321 doesn't work ANYWHERE then an alternate item might just be needed

**Comment by opatut** [comment]
Item 32321 works fine in Dalaran, it does properly react to the distance to target.

Note that in the broken state the function `IsItemInRange` returns `nil` instead of `true` or `false`.  This is the same result I get when I provide an invalid second argument, such as `IsItemInRange(32321, "raid1000")`, or `"target"` while not actually targeting anybody.

I assume the bug relates to the vehicle physics of the airship, hence it breaks when moving onto the ship and back off. I thought this might have been fixed with a special workaround elsewhere, since the game engine is rather old by now and there probably is a similar encounter in some extension ;)

**Comment by MysticalOS** [comment]
Gonna close this issue since blizzard is in process of killing feature off entirely and range frame in its' entirety will be removed from DBM soon.
