### ISSUE TITLE
UnitAura error on Tindral Sageswift LFR Amirdrassil Raid fight with WoW 10.2.5

### ISSUE THREAD

**Issue by mbattersby** [DeadlyBossMods/DBM-Unified#380]
Had this error pop up multiple times on Tindral Sageswift LFR today (multiple times in the same fight and on multiple different attempts at the fight on different characters).

```
Message: bad argument #2 to '?' (outside of expected range 0 to 4294967295 - Usage: local aura = C_UnitAuras.GetAuraDataByIndex(unitToken, index [, filter]))
Time: Wed Jan 17 22:07:07 2024
Count: 32
Stack: bad argument #2 to '?' (outside of expected range 0 to 4294967295 - Usage: local aura = C_UnitAuras.GetAuraDataByIndex(unitToken, index [, filter]))
[string "=[C]"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:6397: in function `UnitDebuff'
[string "@Interface/AddOns/DBM-Core/DBM-InfoFrame.lua"]:639: in function `?'
[string "@Interface/AddOns/DBM-Core/DBM-InfoFrame.lua"]:1155: in function `Show'
[string "@Interface/AddOns/DBM-Raids-Dragonflight/Amirdrassil/TindralSageswift.lua"]:573: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1106: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:1093>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1106: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:1093>

Locals: (*temporary) = "bad argument #2 to '?' (outside of expected range 0 to 4294967295 - Usage: local aura = C_UnitAuras.GetAuraDataByIndex(unitToken, index [, filter]))"
```

Looks like a case overlooked with switching to the new C_UnitAuras.GetAuraDataByIndex version of UnitAura.

**To Reproduce**

1. Queue for LFR Tindral Sageswift.
2. Continue fight until stage 2 Burning Treant form.
3. Tindral casts Suppressive Ember putting a heal absorb on players.
4. Error triggers.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No.

**Which version of DeadlyBossMods are you using?**

DBM 10.2.17 (2024/01/17 06:02:29)

**Was it working in a previous version? If yes, which was the last good one?**

Done this fight many times before today and never seen this error before. Would definitely have been working with 10.2.14 under WoW 10.2.0.

**Additional context**

**Comment by mbattersby** [comment]
FWIW the actual call at the end is

`UnitAura('raid1', "Suppressive Ember", "HARMFUL")`

**Comment by QartemisT** [comment]
This has been fixed. Forgot to close :)
