### ISSUE TITLE
Tooltip verification/icon

### ISSUE THREAD

**Issue by Lacerace** [DeadlyBossMods/DBM-Unified#7]
**Is your feature request related to a problem? Please describe.**

I find in pug groups far too many people don't follow mechanics. This is either their negligence, or they don't use DBM.

**Describe the solution you'd like**

It might reduce the risk involved with pugging if you were to implement a tooltip icon for verification that another player is running dbm much like Raider.io shows other players scores. It could simply be an added assurance that they at least have something that tells them what they need to be doing during boss fights and such.

**Describe alternatives you've considered**

I've considered emailing the makers of Raider.io to suggest they don't give io points to players in dungeons or raids that they are severely undergeared in, encouraging players to learn mechanics and work their way up.

**Additional context**

**Comment by MysticalOS** [comment]
Issue has been open 2 and a half years. safe to say it isn't happening.
